### ISSUE TITLE
 dm/dt stopping value

### ISSUE THREAD

**Issue by talekarpm1** [ubermag/ubermag#99] opened 2019-03-15 06:58 UTC
As that of oommf how to give dm/dt stopping value in joommf program to stop at that particular dm/dt.
will it work if I make changes in driver file
if "derive" in kwargs:
            t, n, s = 1e-25, 1, 0.01
        else:
            t, n, s = kwargs["t"], kwargs["n"], kwargs["s"]

mif += "  stopping_dm_dt {}\n".format(s/n)

Then, it likely would be possible to change it using td.drive(system, t=0.1e-9, n=200, s=0.01).

**Comment by marijanbeg** [comment] 2019-06-14 09:25
This is a duplicate of https://github.com/ubermag/help/issues/30

**Closed by marijanbeg** 2019-06-14 09:25 UTC
